### ISSUE TITLE
Add ability to disable all functionality

### ISSUE THREAD

**Issue by kevintweber-crandkgroup** [grafana/grafana-opentelemetry-starter#35]
Generally, when I am in writing code, I create a Spring profile for local development.  It would be great to be able to disable all functionality for this starter for this one profile, but leave it enabled for higher environments.

Perhaps something like this:

```
grafana:
  otlp:
    enabled: false
```
The default value for enabled should be `true`.

**Comment by zeitlinger** [comment]
thanks - that's a good idea :smile:

**Comment by zeitlinger** [comment]
Feature is part of https://github.com/grafana/grafana-opentelemetry-starter/releases/tag/1.3.2

**Comment by kevintweber-crandkgroup** [comment]
Thanks.  :+1:
